title="CDs"

[dead-shall-reign]
title="Dead Shall Reign"
year=2009
type="EP"
price=300

[slaves-to-the-subliminal]
title="Slaves to the Subliminal"
year=2011
type="Album"
price=1000

[wrath-of-durga]
title="Wrath of Durga"
year=2012
type="Album"
price=1000

[kali-yuga]
title="Kali Yuga"
year=2015
type="Album"
price=1000
